name: CI/CD

on:
  push:
    branches: [deployment]
  pull_request:
    branches: [deployment]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.18.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: Deploy
        run: |
          git config --global user.name "Armin Basirain"
          git config --global user.email $user_email
          git remote set-url origin https://${github_token}@github.com/${repository}
          yarn deploy
        env:
          user_name: 'Armin Basirian'
          user_email: 'ar.basirian@gmail.com'
          github_token: ${{ secrets.REACT_APP_BASE_URL_API }}
          repository: ${{ github.repository }}
