name: Build & deploy

on:
  push:
    branches:
      - deployment
  pull_request:
    branches:
      - deployment

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.18.*

      - name: Install NPM packages
        run: yarn install

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/deployment'

    steps:
      - name: Deploy to gh-pages
        run: yarn deploy
        with:
          github_token: ${{ secrets.REACT_APP_BASE_URL_API }}
          publish_dir: ./build
